# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  web:
    desc: Run Web Application Server
    cmd: cd ./web && bun run dev && cd ../
    silent: true
